In [1]:
import numpy as np
import pandas as pd
import string
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [2]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\E056362\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
filepath = 'C:/Users/E056362/Documents/1 New Project/Datasets/SpamCollection/SpamCollection'

In [4]:
data = pd.read_csv(filepath,sep='\t',header=None,names=['Response','Messages'])
data.head()

Response                                           Messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
data.describe()

Response                Messages
count      5572                    5572
unique        2                    5169
top         ham  Sorry, I'll call later
freq       4825                      30

In [6]:
#1. Calculate the Length 
data['Length'] = data.Messages.str.len()

In [7]:
data.head()

Response                                           Messages  Length
0      ham  Go until jurong point, crazy.. Available only ...     111
1      ham                      Ok lar... Joking wif u oni...      29
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
3      ham  U dun say so early hor... U c already then say...      49
4      ham  Nah I don't think he goes to usf, he lives aro...      61

In [8]:
# 3. Define a function to eliminate stopwords

def eliminate_stopwords(message):
    # Eliminate the Punctuations
    char_Wo_punctuations = [char for char in message if char not in string.punctuation]
    # join 
    Sentence_wo_Punctuation = ''.join(char_Wo_punctuations)
    # Eliminate the stopword and return the clean sentense
    Clean_setense = [word.lower() for word in Sentence_wo_Punctuation.split() 
                     if word.lower() not in stopwords.words('english')]
    return Clean_setense
    

In [9]:
message = 'Ok lar... Joking wif u oni...'
Punctu = [char for char in message if char not in string.punctuation]
sen = ''.join(Punctu)
cleansen = [word.lower() for word in sen.split() if word.lower() not in stopwords.words('english')]

In [10]:
sen

'Ok lar Joking wif u oni'

In [11]:
eliminate_stopwords(message)

['ok', 'lar', 'joking', 'wif', 'u', 'oni']

In [12]:
data["CleanMessage"] = data.Messages.apply(eliminate_stopwords)

In [13]:
data.head()

Response                                           Messages  Length  \
0      ham  Go until jurong point, crazy.. Available only ...     111   
1      ham                      Ok lar... Joking wif u oni...      29   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155   
3      ham  U dun say so early hor... U c already then say...      49   
4      ham  Nah I don't think he goes to usf, he lives aro...      61   

                                        CleanMessage  
0  [go, jurong, point, crazy, available, bugis, n...  
1                     [ok, lar, joking, wif, u, oni]  
2  [free, entry, 2, wkly, comp, win, fa, cup, fin...  
3      [u, dun, say, early, hor, u, c, already, say]  
4  [nah, dont, think, goes, usf, lives, around, t...

In [14]:
# Statr Text Processing with Vectorizer
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(data['Messages'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [15]:
# Display the size of Vocabulary
len(vect.vocabulary_)

8713

In [16]:
# Transform the data
BagOfWords = vect.transform(data['Messages'])

In [17]:
# Get the list of Feature Names
vect.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '084

In [18]:
BagOfWords.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
setense = [data.iloc[0,1],data.iloc[1,1],data.iloc[2,1]]
vect2 = CountVectorizer()

In [28]:
vect2.fit(setense)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [31]:
vect2.vocabulary_

{'go': 17,
 'until': 39,
 'jurong': 22,
 'point': 29,
 'crazy': 11,
 'available': 6,
 'only': 28,
 'in': 20,
 'bugis': 8,
 'great': 19,
 'world': 44,
 'la': 23,
 'buffet': 7,
 'cine': 9,
 'there': 35,
 'got': 18,
 'amore': 4,
 'wat': 40,
 'ok': 26,
 'lar': 24,
 'joking': 21,
 'wif': 41,
 'oni': 27,
 'free': 16,
 'entry': 13,
 'wkly': 43,
 'comp': 10,
 'to': 37,
 'win': 42,
 'fa': 14,
 'cup': 12,
 'final': 15,
 'tkts': 36,
 '21st': 2,
 'may': 25,
 '2005': 1,
 'text': 34,
 '87121': 3,
 'receive': 32,
 'question': 30,
 'std': 33,
 'txt': 38,
 'rate': 31,
 'apply': 5,
 '08452810075over18': 0}

In [33]:
bagofwords = vect2.transform(setense)

In [37]:
bagofwords.toarray()

array([[0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 3, 1, 0, 0, 0, 1, 1,
        0]], dtype=int64)

In [50]:
setense[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [73]:
from sklearn.feature_extraction.text import TfidfTransformer
Tfidf = TfidfTransformer()
TFIDFTransformer = Tfidf.fit(bagofwords)

In [40]:
DocTfidf = Tfidf.transform(bagofwords)

In [41]:
DocTfidf.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.23851206,
        0.        , 0.23851206, 0.23851206, 0.23851206, 0.23851206,
        0.        , 0.23851206, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.23851206, 0.23851206, 0.23851206,
        0.18139457, 0.        , 0.23851206, 0.23851206, 0.        ,
        0.        , 0.        , 0.        , 0.23851206, 0.23851206,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.23851206, 0.        , 0.        , 0.        , 0.23851206,
        0.23851206, 0.        , 0.        , 0.        , 0.23851206],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4472136 , 0.        , 0.        , 0.4472136 ,
        0.        , 0.4472136 , 0.4472136 , 0. 

In [42]:
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()

In [62]:
model = NB.fit(DocTfidf,data.iloc[0:3,0])

In [63]:
data.iloc[0:3,0]

0     ham
1     ham
2    spam
Name: Response, dtype: object

In [76]:
print(setense[:1])
SampleBagOfWords = vect2.transform(setense[:1])
SampleBagOfWords

['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']


<1x45 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [77]:
TFIDF = TFIDFTransformer.transform(SampleBagOfWords)

In [83]:
print('Predicted:',model.predict(TFIDF))

Predicted: ['ham']


In [85]:
print('Expected',data['Response'][0])

Expected ham
