In [49]:
dist=[10,15,17,26]

In [50]:
time=[5,3,2,13]

In [51]:
import numpy as np
    

In [52]:
var1 = np.array(dist)

In [53]:
var2 = np.array(time)

In [54]:
var1/var2

array([2. , 5. , 8.5, 2. ])

In [59]:
var1

array([10, 15, 17, 26])

In [94]:
array=(1,2,3,4,5,6,7,8,9,10)

In [100]:
a=np.array(array)

In [127]:
type(array)

tuple

In [101]:
a[-1]

10

In [123]:
arr=np.reshape(a,(2,5))

In [124]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [126]:
arr[1,3]

9

In [129]:
for i in arr:
     
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
